apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache2
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:latest # Official Apache2 image from Docker Hub
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache2-service
  namespace: default
spec:
  selector:
    app: apache2
  ports:
    - protocol: TCP
      port: 80        # The port the service will expose
      targetPort: 80  # The port the pods are
  type: LoadBalancer
